language: node_js
node_js:
  - "node"
before_install:
  - npm install -g @lhci/cli
  - npm install -g gulp-cli
script:
  - npm run dist # build your site
  - lhci autorun --rc-overrides.upload.target=temporary-public-storage # run lighthouse CI
addons:
  chrome: stable # make sure you have Chrome available
