language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
before_install:
  - npm install -g @lhci/cli
  - npm install -g gulp-cli
script:
  - npm run dist
after_success:
  - lhci autorun
addons:
  chrome: stable # for lighthouse
